### ISSUE TITLE
UI design delibration

### ISSUE THREAD

**Issue by Dablaze-ufc** [Dablaze-ufc/naijahacks-educationapp#1]
# NaijaHacks Hackathon 2019

**Comment by Dablaze-ufc** [comment]
![Screenshot from 2019-12-08 20-21-22](https://user-images.githubusercontent.com/52836046/70395119-db99d900-19fb-11ea-8833-812322a684b5.png)

**Comment by segunfrancis** [comment]
I suggest you make the width of the small video box match the width of the card that holds it and also adjust the width of the progress bar to match the width of the card.
